version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: curriculum-frontend
    container_name: curriculum-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped