version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: meu-app-nextjs
    container_name: meu-app-nextjs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm run dev